-- V2.0.0__grants.sql

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA app TO aairp_migration;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA app TO aairp_app;
GRANT SELECT ON ALL TABLES IN SCHEMA app TO aairp_readonly;

GRANT SELECT, INSERT ON ALL TABLES IN SCHEMA audit TO aairp_migration;
GRANT SELECT, INSERT ON audit.audit_event TO aairp_app;
GRANT SELECT ON audit.audit_event TO aairp_readonly;

ALTER DEFAULT PRIVILEGES IN SCHEMA app
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO aairp_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA audit
    GRANT SELECT, INSERT ON TABLES TO aairp_app;
